import pandas as pd
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)

# read in both excel files into pandas dataframes
md_files = pd.read_excel('G:\\datasets\\mining_district\\mining_district_files_12202019.xlsx')
commodities = pd.read_excel('G:\\datasets\\mining_district\\nv_commodities.xlsx')

# take a look at unique values in the mining district files commodities list
comm_list = md_files.commodity.str.cat(sep="; ")
comm_list_arr = comm_list.split("; ")
comm_list_arr = np.unique(comm_list_arr, axis=0)

# identify values that are in the mining district file spreadsheet but NOT in the commodities master list

#first, change lists to sets and make them all lower case for comparison
lower_md_comm = {item.lower() for item in comm_list_arr}
lower_gen_comm = {item.lower() for item in commodities.name}

#find out what values are in the mining district files that do overlap with the commodities master list, and which ones don't
not_in = lower_md_comm.difference(lower_gen_comm)
intersection = lower_md_comm.intersection(lower_gen_comm)

df=pd.DataFrame(md_files)
df.replace(to_replace ='BAIRITE', value ="BARYTE") 

df=pd.DataFrame(lower_gen_comm)
df.replace(to_replace = 'molybdenium', value= 'molybdenum')
df.replace(to_replace= 'vanandinite', value='vanadinite')
df.replace(to_replace= 'soduim', value='sodium')
df.replace(to_replace='lead tungston', value='lead tungsten')
df.replace(to_replace='leaseable', value='leasable')
df.replace(to_replace='wallastonite', value='wollastonite')
df.replace(to_replace='neodynium', value='neodymium')
df.replace(to_replace='copper tungston', value='copper tungsten')
df.replace(to_replace='kuroko base metal deposit', value='kuroko deposit')
df.replace(to_replace='uraniforous', value='uraniferous')
df.replace(to_replace='sodium sufate', value='sodium sulfate')

df=pd.DataFrame(lower_md_comm)
df.replace(to_replace='platimun', value='platinum')
df.replace(to_replace='tunsten', value='tungsten')
df.replace(to_replace='silca sand',value='silica sand')
df.replace(to_replace='murcury', value='mercury')
df.replace(to_replace='glod', value='gold')
df.replace(to_replace='hornsilver', value='horn silver')
df.replace(to_replace='magnesiuim', value= 'magnesium')
df.replace(to_replace='varicite', value='variscite')
df.replace(to_replace='fluorspar;barite', value='fluorspar; barite')
df.replace(to_replace='fledspar', value='feldspar')
df.replace(to_replace='bitumens', value='bituminous minerals')
df.replace(to_replace='fluroite', value= 'fluorite')
df.replace(to_replace='lead-sillver', value= 'lead-silver')
df.replace(to_replace='hgold', value='gold')
df.replace(to_replace='cpper', value='copper')
df.replace(to_replace='artimony', value='antimony')
df.replace(to_replace='coppper', value='copper')
df.replace(to_replace='molybdeum', value='molybdneum')
df.replace(to_replace='flourite', value='fluorite')
df.replace(to_replace='sheelite', value='scheelite')
df.replace(to_replace='chlorargyite', value='chlorargyrite')
df.replace(to_replace='malacite', value='malachite')
df.replace(to_replace='mangansese', value='manganese')
df.replace(to_replace='vanandinite', value='vanadinite')
df.replace(to_replace='soduim nitrate', value='sodium nitrate')
df.replace(to_replace='flurotie', value='fluorite')
df.replace(to_replace='tungston', value='tunsten')
df.replace(to_replace='wolastonite', value='wollastonite')
df.replace(to_replace='mangnaese', value='manganese')
df.replace(to_replace='molybdemum', value='molybdenum')
df.replace(to_replace='silver;copper', value='silver; copper')
df.replace(to_replace='wulphur', value='sulphur')
df.replace(to_replace='cerrusite', value='cerrussite')
df.replace(to_replace='zince', value= 'zinc')
df.replace(to_replace='ainc', value='zinc')
df.replace(to_replace='paladium', value='palladium')
df.replace(to_replace='salines', value= 'saline minerals')
df.replace(to_replace='cpidote', value= 'epidote')
df.replace(to_replace='batite', value='barite')
df.replace(to_replace='ceragyrite', value='cerargyrite')
df.replace(to_replace='liemstone', value='limestone')
df.replace(to_replace='ismium', value='osmium')
df.replace(to_replace='pumacite', value='pumicite')
df.replace(to_replace='cuo', value= 'copper oxide')
df.replace(to_replace='siler', value='silver')
df.replace(to_replace='rungsten', value='tungsten')
df.replace(to_replace='goldl', value='gold')
df.replace(to_replace='phospherous', value='phosphorous')
df.replace(to_replace='marganese', value='manganese')
df.replace(to_replace='wollastorite', value='wollastonite')
df.replace(to_replace='molybdenyum', value='molybdenum')
df.replace(to_replace='goled', value='gold')

df.replace(to_replace= 'andelusite', value= 'andalusite')
df.replace(to_replace='flurine', value='fluorine')
df.replace(to_replace='diatomaceaous', value= 'diatomaceous' )
df.replace(to_replace='leaseable', value='leasable' )
df.replace(to_replace='dolomite;dolomitic;limestone;calcitic dolomite', value='dolomite; dolomitic; limestone; calcitic dolomite')
df.replace(to_replace='molybedeaum', value='molybdenum')
df.replace(to_replace='milybdenum', value= 'molybdenum')
df.replace(to_replace='chlorite;talc;calcite', value='chlorite; talc; calcite')
df.replace(to_replace='coppeer', value= 'copper')
df.replace(to_replace='clay;talc', value='clay; talc')
df.replace(to_replace='brucitite-magnesite', value='brucite-magnesite')
df.replace(to_replace='wolfenite', value= 'wulfenite')
df.replace(to_replace='silver sulfides and preciuos-metals', value='silver sulfides and precious-metals')
df.replace(to_replace='maganese', value='manganese')
df.replace(to_replace='casserite', value='cassiterite')
df.replace(to_replace='florite', value='fluorite')
df.replace(to_replace='antomony', value='antimony')
df.replace(to_replace='mercry', value='mercury')
df.replace(to_replace='potussium chloride', value='potassium chloride')
df.replace(to_replace='phos-o', value='phosphorus')
df.replace(to_replace='tugnsten', value='tungsten')
df.replace(to_replace='gysum', value='gypsum')
df.replace(to_replace='stivnite', value='stibnite')
df.replace(to_replace='tugsten', value='tungsten')
df.replace(to_replace='vanadenite', value='vanadinite')
df.replace(to_replace='arsenci', value='arsenic')
df.replace(to_replace='bairte', value='barite')
df.replace(to_replace='calcite;dolomite;sepiolite;silicate;mg clay', value='calcite; dolomite; sepiolite; silicate; magnesium clay')
df.replace(to_replace='sercite', value='sericite')
df.replace(to_replace='molyhdenum',value='molybdenum')
df.replace(to_replace='golq', value='gold')
df.replace(to_replace='coopper', value='copper')
df.replace(to_replace='copper;bairite', value='copper; barite')
df.replace(to_replace='posellite', value='powellite')
df.replace(to_replace='tellinium', value='tellurium')
df.replace(to_replace='silver-sinc-lead', value='silver-zinc-lead')
df.replace(to_replace='tungiten', value='tungsten')
df.replace(to_replace='siilver', value='silver')
df.replace(to_replace='laead', value='lead')
df.replace(to_replace='montmorillinitic clay', value='montmorillonite clay')
df.replace(to_replace='wallastonite', value='wollastonite')
df.replace(to_replace='modybdenum', value='molybdenum')
df.replace(to_replace='silve', value='silver')
df.replace(to_replace='sulphur deposites', value='sulphur')
df.replace(to_replace='tunsgten', value='tungsten')
df.replace(to_replace='talc;chlorite', value='talc; chlorite')
df.replace(to_replace='mersury', value='mercury')
df.replace(to_replace='sodium sufate', value='sodium sulfate')
df.replace(to_replace='sulphides', value='sulfides')
df.replace(to_replace='sulvides and precious metals', value='sulfides and precious metals')
df.replace(to_replace='uranium, copper, nickle, cobalt', value='uranium, copper, nickel, cobalt')
df.replace(to_replace='vanadiuml zinc', value='vanadium zinc')
df.replace(to_replace='diamtomite', value='diatomite')
df.replace(to_replace='fluroite;gold', value='fluroite; gold')
df.replace(to_replace='vanudium', value='vanadium')
df.replace(to_replace='siver', value='silver')
df.replace(to_replace='betonite', value='bentonite')
df.replace(to_replace='arsencic', value='arsenic')
df.replace(to_replace='chrysacolla', value='chrysocolla')
df.replace(to_replace='colbalt', value='cobalt')
df.replace(to_replace='volcanid ash', value='volcanic ash')

df=pd.DataFrame(intersection)
df.replace(to_replace='soduim nitrate', value='sodium nitrate')
df.replace(to_replace='sodium sufate', value='sodium sulfate')
df.replace(to_replace='leaseable minerals', value='leasable minerals')


df=pd.DataFrame(comm_list_arr)
df.replace(to_replace='AND MINOR AMMOUNTS OF MERCURY', value='AND MINOR AMOUNTS OF MERCURY')
df.replace(to_replace='ZINC (?)', value='ZINC')
df.replace(to_replace='ANDELUSITE',value='ANDALUSITE')
df.replace(to_replace='ANTIMONY?', value='ANTIMONY')
df.replace(to_replace='ANTOMONY', value='ANTINOMY')
df.replace(to_replace= 'ARSENCI', value= 'ARSENIC')
df.replace(to_replace= 'ARSENCIC',value= 'ARSENIC')
df.replace(to_replace= 'ARSNIC',value= 'ARSENIC')
df.replace(to_replace='ARTIMONY', value='ANTINOMY')
df.replace(to_replace='AU', value= 'GOLD')
df.replace(to_replace='AU, AG', value= 'GOLD, SILVER')
df.replace(to_replace='BAIRTE', value= 'BARITE')
df.replace(to_replace='BAIRTE(?)', value= 'BARITE')
df.replace(to_replace= 'BATITE', value= 'BARITE')
df.replace(to_replace='BERRYLIUM', value= 'BERYLLIUM')
df.replace(to_replace='BETONITE', value='BENTONITE')
df.replace(to_replace='BARIUM (?)', value='BARIUM')
df.replace(to_replace='ANTIMONY (?)', value='ANTIMONY')
df.replace(to_replace='BORATES (?)', values='BORATES')
df.replace(to_replace='CASSERITE', values='CASSITRITE')
df.replace(to_replace='CERRUSITE', values='CERUSSITE')
df.replace(to_replace='CHLORARGYITE', values='CHLORARGRITE')
df.replace(to_replace= 'CHROMIUM (?)', values= 'CHROMIUM')
df.replace(to_replace='CHRYSACOLLA', value='CHRYSOCOLLA')
df.replace(to_replace='COLBALT', value= 'COBALT')
df.replace(to_replace='COOPPER', value= 'COPPER')
df.replace(to_replace='COPER'., value= 'COPPER')
df.replace(to_replace='COPPEER'., value= 'COPPER')
df.replace(to_replace='COPPER (?)'., value= 'COPPER')
df.replace(to_replace='COPPER Oxides (?)'., value= 'COPPER')
df.replace(to_replace='COPPER?'., value= 'COPPER')
df.replace(to_replace='COPPPER'., value= 'COPPER')
df.replace(to_replace='CPPER'., value= 'COPPER')
df.replace(to_replace='CPIDOTE', value='EPIDOTE')
df.replace(to_replace='DIAMTOMITE', value='DIATOMITE')
df.replace(to_replace='DIATOMACEAOUS EARTH', values='DIATOMACEOUS EARTH')
df.replace(to_replace='DISSEMINATED GOLD (?)', value='DISSEMINATED GOLD')
df.replace(to_replace='FLEDSPAR', value='FELDSPAR')
df.replace(to_replace='FLORITE', value='FLUORITE')
df.replace(to_replace='FLOURITE', value='FLUORITE')
df.replace(to_replace='FLUORITE (?)', value='FLUORITE')
df.replace(to_replace='FLUORINE (?)', value='FLUORINE')
df.replace(to_replace='FLURINE', value='FLUORINE')
df.replace(to_replace='FLUROITE', value='FLUORITE')
df.replace(to_replace='FLUROITE;GOLD', value= 'FLUORITE; GOLD')
df.replace(to_replace='FLUROTIE', value='FLUORITE')
df.replace(to_replace='GEM QUALITY JASPER (?)', value= 'GEM QUALITY JASPER')
df.replace(to_replace='GLOD',value= 'GOLD')
df.replace(to_replace='GOD',value= 'GOLD')
df.replace(to_replace='GOLD (?)',value= 'GOLD')
df.replace(to_replace='PHOSPHEROUS', value= 'PHOSPHORUS')
df.replace(to_replace='GLOLD',value= 'GOLD')
df.replace(to_replace='GOLED',value= 'GOLD')
df.replace(to_replace='GOLQ',value= 'GOLD')
df.replace(to_replace='GYSUM', value='GYPSUM')
df.replace(to_replace='HGOLD', value='HORN GOLD')
df.replace(to_replace='IRIGIUM', valule='IRIDIUM')
df.replace(to_replace='ISMIUM', value='OSMIUM')
df.replace(to_replace='JASPEROID (?)', value= 'JASPEROID')
df.replace(to_replace='LAEAD', value='LEAD')
df.replace(to_replace='LEAD-SILLVER', value='LEAD-SILVER')
df.replace(to_replace='LEASEABLE MINERALS', value= 'LEASABLE MINERALS')
df.replace(to_replace='LIEMSTONE',value='LIMESTONE')
df.replace(to_replace='MAGANESE', value='MANGANESE')
df.replace(to_replace='MAGNESIA ALUM', value='MAGNESIA ALUMINA')
df.replace(to_replace='MAGNESIUIM', value='MAGNESIUM')
df.replace(to_replace='MALACITE', value='MALACHITE')
df.replace(to_replace='MANGANE4SE', value='MANGANESE')
df.replace(to_replace='MANGANESE (?)', value='MANGANESE')
df.replace(to_replace='MANGANSESE', value='MANGANESE')
df.replace(to_replace='MANGNAESE', value='MANGANESE')
df.replace(to_replace='MARGANESE', value='MANGANESE')
df.replace(to_replace='MERSURY', value= 'MERCURY')
df.replace(to_replace='MILYBDENUM',value='MOLYBDENUM')
df.replace(to_replace='MERCURY (?)', value= 'MERCURY')
df.replace(to_replace='MODYBDENUM',value='MOLYBDENUM')
df.replace(to_replace='MOLBDENUM',value='MOLYBDENUM')
df.replace(to_replace='MOLBDENUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYBDEMUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYBDEUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYBEDEAUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYBEDUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYBENUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYHDENUM',value='MOLYBDENUM')
df.replace(to_replace='MOLYNDENUM',value='MOLYBDENUM')
